version: '3.8'

services:
  web:
    image: nar001/devops-visitor-app:latest
    ports:
      - "8080:5000" #maps port 8080 to container port 5000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: "redis:alpine" #pulls redis image from DockerHub
    ports:
      - "6379:6379"
